# Test file to learn simple GitHub Action workflow
# This as part of investigating the libyang README.md which was observed to say "oss-fuzz build failing"
name: Hello Action

on:
  push:       # Runs every time you push to the repo
  pull_request:

jobs:
  say_hello:
    runs-on: ubuntu-latest   # GitHub-hosted runner
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true  # Forces Node 24 for JS actions. Attempt to suppress warning that Node.js 20 is deprecated.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Safely fetches your repo code

      - name: Say hello
        run: |
          echo "Hello from GitHub Actions!" >> HelloOutput.txt

